### PR TITLE
Fix broken link to build docs

### PR DESCRIPTION
**Pull request by ThomasMarcelis**
Just a small linking error I found while reading in the docs :)

### CODE REVIEW

**Comment by ZapBlasterson** [comment]
Thank you for the fix!

The markdown files in /docs/ are also served by the CrushPaper server under the "Help" link. Unfortunately if I merge this pull request it will break the links in files when they are served by the CrushPaper server. To make sure the links work in both contexts. I think all of the links in the /docs/ directory have to be updated as you have done and the CrushPaper server has to be changed so to rewrite the URLs.

**Comment by ThomasMarcelis** [comment]
Oh, I see. I just went straight to github to read the docs and didn't realise this also gets served on the website, went a bit too quick there. Exciting project by the way!

**Comment by ZapBlasterson** [comment]
No worries and thank you!

If you have any more thoughts I would love to hear them.

**Comment by ZapBlasterson** [comment]
I just committed a fix for all of these links like we discussed a few days ago.

Thank you again for pointing this out!

**Pull request closed without merging**
